Feature/issue 30
shuiro-dev/shuiro pull request #156
Opened 2024-10-31 08:44 UTC by Texiko-texiko

2024-11-27 14:45 UTC, r4ai requested changes

2024-11-27 14:45 UTC, r4ai commented on frontend/src/routes/admin/submissions/$submissionId/-components/submissioned-code/submissioned-code.tsx
imo: submissionedという英語は存在しないので、submitted-code-infoやsubmitted-codeなどに名前を変えた方が分かりやすいと思います！

2024-11-27 14:45 UTC, r4ai commented on frontend/src/routes/admin/submissions/$submissionId/route.lazy.tsx
> +        <div className="flex flex-1 flex-col">
imo: 左右のカードの間にも余白を入れてあげた方が見やすいかなと思いました！

```suggestion
        <div className="flex flex-1 flex-col gap-6">
```

2024-11-27 14:45 UTC, r4ai commented on frontend/src/routes/admin/submissions/$submissionId/-components/submissioned-code/submissioned-code.tsx
> +      </CardContent>
imho: コピーボタンの位置が少し崩れているように感じたので、コードブロックの中の右上などに置いた方が分かりやすいような気がしました？人によって違う気がするのでこれについて意見を聞きたいです

![image](https://github.com/user-attachments/assets/16d7a1ff-b373-4ab9-8a6e-de08744db6af)

2024-11-28 09:48 UTC, r4ai approved these changes
LGTM!

2024-11-28 19:09 UTC, sou1118 submitted a review, later dismissed

2024-12-02 07:50 UTC, sou1118 approved these changes
LGTM!

2024-12-02 13:42 UTC, r4ai approved these changes

2024-12-02 13:42 UTC, merged